# Generated by Django 2.1.9 on 2019-12-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='user_tag_transactions', to='walletapp.UserTransactionTag'),
        ),
    ]
