# Generated by Django 2.1.9 on 2019-12-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0005_auto_20191216_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfo',
            name='account_holder',
        ),
        migrations.DeleteModel(
            name='AccountInfo',
        ),
    ]
