# Generated by Django 2.1.9 on 2019-12-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0006_auto_20191216_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_income',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
